# Generated by Django 4.1 on 2022-08-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('work_address', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('detail_link', models.CharField(max_length=100)),
            ],
        ),
    ]
